name: Template Removal Request
description: Request template removal
labels: [remove-template]
body:
  - type: input
    id: npm_name
    attributes:
      label: "npm package name"
    validations:
      required: true
