name: Template Update Request
description: Request to update template
labels: [update-template]
body:
  - type: input
    id: npm_name
    attributes:
      label: "npm package name"
    validations:
      required: true
