name: Template Review Request
description: Request template verification
labels: [add-template]
body:
  - type: input
    id: github_link
    attributes:
      label: "Link to GitHub repo"
      placeholder: https://github.com/xxx
    validations:
      required: true
  - type: input
    id: npm_name
    attributes:
      label: "Name of NPM package"
    validations:
      required: true
