name: Reusable Workflow For Checking Permissions

on:
  workflow_call:
    inputs:
      user-login:
        required: true
        type: string
      npm-package:
        required: true
        type: string
      github-repo-owner:
        required: true
        type: string
      github-repo:
        required: true
        type: string
    outputs:
      is-admin-error:
        value: ${{ jobs.is-admin.outputs.error }}
      is-admin:
        value: ${{ jobs.is-admin.outputs.is-admin }}

defaults:
  run:
    shell: bash

jobs:
  is-admin:
    name: Check if an issue submitted or commented by a Github user with admin permissions
    runs-on: ubuntu-latest
    outputs:
      error: ${{ steps.is-admin.outputs.error }}
      is-admin: ${{ steps.is-admin.outputs.is-admin }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Use node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Validate creator of request is admin
        id: is-admin
        env:
          USER_LOGIN: ${{ inputs.user-login }}
          ALLOWLIST_ADMINS: ${{ vars.ALLOWLIST_ADMINS }}
        run: |
          node src/is-admin.js "$USER_LOGIN"
