name: Validate All Templates

on:
  workflow_dispatch:

jobs:
  validate-templates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Print
        run: env | sort
      - name: Validate templates
        id: validate-templates
        run: |
          node src/validate-all-templates.js > failed-templates.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
      - name: Create "Manual Run Results" Issue
        if: failure()
        uses: imjohnbo/issue-bot@v3.3.6
        id: issue
        with:
          title: 'Manual Run Results'
          body: |
              Failed templates:
              ```
              $(cat failed-templates.txt)
              ```
          pinned: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
